### ISSUE TITLE
Use Public Docker Image in CI: issues in forks

### ISSUE THREAD

**Issue by e1turin** [secs-dev/xv6-riscv#16]
Нужно исправить конфиг GitHub Actions, чтобы там использовался публичный образ типа `vityamand/xv6`, чтобы не нужно было делать дополнительные махинации с токенами и всё автоматически работало после форка (см. 1.). Стоит добавить автоматическую сборку и использование собранного образа (см. 2.).

**References**: 

1. https://github.com/secs-dev/xv6-riscv/compare/main...deevroman:xv6-riscv:main
2. https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/.github/workflows/docker_2204.yml

**Comment by vityaman** [comment]
@e1turin, it is not so obvious when tests are depend on changes in this image. We use it as a basement for CI job, but do not want to push it actually until it merged into main.
