### ISSUE TITLE
Add lab instructions

### ISSUE THREAD

**Issue by vityaman** [secs-dev/xv6-riscv#2]
At least copy-paste that `.pdf` files here. Maybe rewrite them to markdown.

Needed docs:
- [ ] Installation and first boot guide.
- [ ] Development environment guide.
- [ ] Lab 1: ping-pong instructions.
- [ ] Lab 2: memalloc instructions.
- [ ] Lab 3: cow-fork instructions.

**Comment by vityaman** [comment]
I have it at my repo https://github.com/vityaman-edu/os-xv6-riscv/tree/dev/doc

**Comment by e1turin** [comment]
I have some useful comments in my repo https://github.com/e1turin/itmo-os-xv6-riscv/
